// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./../src/components/common/DarkModeContainer.vue')['default']
    HoverContainer: typeof import('./../src/components/common/HoverContainer.vue')['default']
    IconRiCheckLine: typeof import('~icons/ri/check-line')['default']
    IconRiForbidLine: typeof import('~icons/ri/forbid-line')['default']
    IconRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IconRiNotificationBadgeFill: typeof import('~icons/ri/notification-badge-fill')['default']
    IconRiSunFill: typeof import('~icons/ri/sun-fill')['default']
    IconRiSunLine: typeof import('~icons/ri/sun-line')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default']
    SystemLogo: typeof import('./../src/components/common/SystemLogo.vue')['default']
    Test: typeof import('./../src/components/test/index.vue')['default']
  }
}
